### ISSUE TITLE
Assistants > New assistant... has JavaScript error

### ISSUE THREAD

**Issue by Mike-Wood** [chieapp/chie#17]
Chie Version: 0.2.9
Operating System: Ubuntu 20.04

Hey there,

After a brand new install on Ubuntu, I get a JS error when I click: Assistants > New assistant...

Here's a GIF:
![Chie bug](https://github.com/chieapp/chie/assets/11504707/61265cf7-4f4d-4cbb-b7bf-6cdf8638abc8)

BTW, I highly recommend using Rollbar to automatically report NodeJS errors like this. I use it in my personal projects, and it's free :)

**Comment by zcbenz** [comment]
Thank for reporting the bug! I'll also give Rollbar a look :)

Closed with 6cfe7cc.
